# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Shannon Entropy:
#'
#' Rcpp Implementation of a Shannon Entropy
#' http://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf
#'
#' @name conditionalEntropy
#' @param x Numeric vector
#' @param y Numeric vector
#' @return conditional entropy H(X|Y)
#' @export
#'
shannonEnDiscrete <- function(x, normalize, discretize) {
    .Call('_MethQuant_shannonEnDiscrete', PACKAGE = 'MethQuant', x, normalize, discretize)
}

#' Sample Entropy
#'
#' Rcpp Implementation of a Sample Entropy (// https://journals.physiology.org/doi/full/10.1152/ajpheart.2000.278.6.h2039)
#' Implementation adapted from: http://blog.schochastics.net/post/sample-entropy-with-rcpp/
#'
#' @name conditionalEntropy
#' @param x Numeric vector
#' @param y Numeric vector
#' @return conditional entropy H(X|Y)
#' @export
#'
sampleEn <- function(x, m, r) {
    .Call('_MethQuant_sampleEn', PACKAGE = 'MethQuant', x, m, r)
}

mhl <- function(x) {
    .Call('_MethQuant_mhl', PACKAGE = 'MethQuant', x)
}

